"""SourceMind — inspect the evidence behind every answer."""
from __future__ import annotations
import json
import logging
import os
from pathlib import Path
import streamlit as st
from dotenv import load_dotenv
from sourcemind.auth import (AuthExpired, OAuthStateStore, accept_session, clear_session,
                            ensure_session, finish_google, new_client, start_google)
from sourcemind.engine import answer, contradiction_scan, omission_experiment
from sourcemind.ingestion import read_pdf, read_url
from sourcemind.repository import Repository
from sourcemind.browser_binding import browser_binding
from sourcemind.providers import run_model

load_dotenv()
st.set_page_config(page_title="SourceMind", page_icon="◈", layout="wide")
LOG = logging.getLogger("sourcemind")
st.markdown("""<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');
html,body,[class*="css"] {font-family:'DM Sans',sans-serif;}
.stApp {background:#101215;color:#eceef2;}
[data-testid="stHeader"] {background:transparent;}
[data-testid="stSidebar"] {background:#17191d;border-right:1px solid #292c32;}
[data-testid="stMainBlockContainer"] {max-width:960px;padding-top:2rem;}
[data-testid="stSidebar"] [data-testid="stButton"] button {width:100%;justify-content:flex-start;border:0;background:transparent;border-radius:8px;min-height:2.4rem;box-shadow:none;}
[data-testid="stSidebar"] [data-testid="stButton"] button:hover {background:#292c32;}
[data-testid="stSidebar"] [data-testid="stButton"] button[kind="primary"] {background:#30343b;color:#fff;}
.st-key-sidebar-chats [data-testid="stButton"] button p {white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;max-width:100%;font-size:.88rem;}
.st-key-sidebar-chats [data-testid="stButton"] button {display:block;padding:.55rem .75rem;}
[data-testid="stSidebarUserContent"] > div > [data-testid="stVerticalBlockBorderWrapper"] > [data-testid="stVerticalBlock"] {height:calc(100dvh - 110px);gap:.75rem;}
[data-testid="stSidebarUserContent"] > div > [data-testid="stVerticalBlockBorderWrapper"] > [data-testid="stVerticalBlock"] > [data-testid="stVerticalBlockBorderWrapper"]:has(>.st-key-sidebar-chats) {flex:1;min-height:0;overflow-y:auto;}
.st-key-sidebar-nav {gap:.3rem;}
.st-key-sidebar-chats {gap:.2rem;}
.st-key-sidebar-account {padding-top:.6rem;border-top:1px solid #30343b;}
[data-testid="stSidebar"] [data-testid="stPopoverButton"] {width:100%;justify-content:flex-start;border:0;background:transparent;}
[data-testid="stSidebar"] [data-testid="stPopoverButton"]:hover {background:#292c32;}
[data-testid="stChatMessage"] {background:transparent;padding:.75rem 0;}
[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) {background:#23262c;border-radius:18px;padding:1rem 1.2rem;}
[data-testid="stChatInput"] {border-radius:20px;}
[data-testid="stExpander"] {border-color:#30343b;}
.welcome {text-align:center;padding:14vh 0 3rem;}
.welcome h1 {font-size:2rem;font-weight:600;letter-spacing:-.04em;}
.welcome p {color:#a4a8b2;font-size:1rem;}
h1 {letter-spacing:-.05em;}
.eyebrow {color:#67e8c4;font-size:.78rem;letter-spacing:.18em;text-transform:uppercase;}
.hero {font-size:3.2rem;font-weight:700;letter-spacing:-.06em;margin:0;}
.deck {color:#a6b7d0;max-width:720px;font-size:1.1rem;line-height:1.6;}
.stButton>button[kind="primary"] {background:#41d9b0;color:#051b16;border:0;}
@media(max-width:640px) {[data-testid="stMainBlockContainer"] {padding:1.2rem 1rem;}.welcome {padding-top:8vh;}}
</style>""", unsafe_allow_html=True)


def config(key: str, default: str = "") -> str:
    try:
        return str(st.secrets.get(key, os.environ.get(key, default)))
    except FileNotFoundError:
        return os.environ.get(key, default)


def client():
    if "supabase_client" not in st.session_state:
        st.session_state["supabase_client"] = new_client(config("SUPABASE_URL"), config("SUPABASE_PUBLISHABLE_KEY") or config("SUPABASE_ANON_KEY"))
    return st.session_state["supabase_client"]


@st.cache_resource
def encoder():
    os.environ.setdefault("USE_TF", "0")
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")


def embed(text: str) -> list[float]:
    return encoder().encode(text, normalize_embeddings=True).tolist()


def model(system: str, payload: dict) -> dict:
    return run_model(config("GROQ_API_KEY"), config("GROQ_MODEL", "openai/gpt-oss-20b"),
                     system, payload, fallback=config("GROQ_FALLBACK_MODEL", "openai/gpt-oss-120b"))


def failure(action: str, exc: Exception):
    # Provider errors can include private input or credentials: log type only.
    LOG.warning("%s failed (%s)", action, type(exc).__name__)
    if isinstance(exc, AuthExpired):
        # These messages are generated by our own guards and contain no tokens.
        LOG.warning("Authentication guard: %s", str(exc))
        st.error(str(exc))
        return
    text = str(exc).lower()
    if "invalid login" in text:
        st.error("The email or password is incorrect.")
    elif "email not confirmed" in text:
        st.error("Confirm your email before signing in.")
    elif "rate" in text or "429" in text:
        st.error("The service is busy or its rate limit was reached. Please try again shortly.")
    elif "3000" in text:
        st.error("Your knowledge base reached 3,000 passages. Remove a source before adding more.")
    elif "schema cache" in text or "does not exist" in text:
        st.error("The database upgrade has not been applied. Contact the app owner.")
    else:
        st.error(f"{action} could not finish. Please retry.")


def oauth_store():
    return OAuthStateStore(Path(".sourcemind") / "oauth.sqlite")


def oauth_callback():
    if st.session_state.get("auth_callback_done"):
        # Community Cloud remounts its app iframe when st.query_params changes.
        # Its wrapper also intercepts history replacement. Keep the consumed,
        # one-use code until sign-out so the JWT stays on this connection.
        # Neither access nor refresh tokens are ever put in the URL.
        return
    if "error" in st.query_params:
        st.query_params.clear()
        st.warning("Google sign-in was canceled or refused. Try email sign-in or start again.")
    if "code" in st.query_params:
        binding = browser_binding("read", key="oauth_return")
        if binding is None:
            st.info("Completing secure Google sign-in…")
            st.stop()
        try:
            response = finish_google(client(), st.query_params["code"], st.query_params.get("oauth_state", ""),
                                     oauth_store(), binding.get("nonce", ""))
            accept_session(st.session_state, response)
            st.session_state["auth_callback_done"] = True
        except Exception as exc:
            st.session_state["oauth_failed"] = str(exc) if isinstance(exc, AuthExpired) else "Google sign-in could not finish. Start again in this browser."
            failure("Google sign-in", exc)
        finally:
            if not st.session_state.get("user"):
                st.query_params.clear()
        if st.session_state.get("user"):
            st.rerun()
    if "token_hash" in st.query_params:
        try:
            kind = st.query_params.get("type", "email")
            if kind not in {"email", "signup", "recovery"}:
                raise ValueError("Invalid verification type")
            response = client().auth.verify_otp({"token_hash": st.query_params["token_hash"], "type": kind})
            accept_session(st.session_state, response)
            st.session_state["auth_callback_done"] = True
            st.session_state["recovery"] = kind == "recovery"
        except Exception as exc:
            failure("Email verification", exc)
        finally:
            if not st.session_state.get("user"):
                st.query_params.clear()
        if st.session_state.get("user"):
            st.rerun()


def hero():
    st.markdown("<p class='eyebrow'>Private knowledge · Visible evidence</p><p class='hero'>SourceMind</p>", unsafe_allow_html=True)
    st.markdown("<p class='deck'>Answers from your documents, with sources you can check.</p>", unsafe_allow_html=True)


def login_page():
    hero()
    sign_in, sign_up, recover, lab = st.tabs(["Sign in", "Create account", "Reset password", "Explore the Evidence Lab"])
    configured = bool(config("SUPABASE_URL") and (config("SUPABASE_PUBLISHABLE_KEY") or config("SUPABASE_ANON_KEY")))
    with sign_in:
        st.subheader("Welcome to your private workspace")
        if st.session_state.get("oauth_failed"):
            st.error(st.session_state.pop("oauth_failed"))
        if not configured:
            st.info("Account access is awaiting database configuration. The Evidence Lab is available to explore.")
        with st.form("login", clear_on_submit=True):
            email = st.text_input("Email", max_chars=254)
            password = st.text_input("Password", type="password")
            submitted = st.form_submit_button("Sign in", type="primary", disabled=not configured)
        if submitted:
            try:
                if not email.strip() or not password:
                    raise ValueError("Email and password required")
                accept_session(st.session_state, client().auth.sign_in_with_password({"email": email.strip(), "password": password}))
                st.rerun()
            except Exception as exc:
                failure("Sign-in", exc)
        if config("ENABLE_GOOGLE_AUTH", "true").lower() == "true" and configured:
            if st.button("Prepare Google sign-in"):
                try:
                    url, nonce = start_google(client(), config("REDIRECT_URL", "https://adaptive-rag1.streamlit.app/"), oauth_store())
                    st.session_state["google_url"] = url
                    st.session_state["google_nonce"] = nonce
                except Exception as exc:
                    failure("Google sign-in", exc)
            if st.session_state.get("google_url"):
                # Browser-bound state prevents a callback link opened in another
                # browser from signing that browser into the initiator's account.
                nonce = st.session_state["google_nonce"]
                binding = browser_binding("write", nonce, key=f"oauth_start_{nonce}")
                if binding and binding.get("ready"):
                    st.link_button("Continue with Google", st.session_state["google_url"])
                elif binding is not None:
                    st.error("Allow site cookies to use Google sign-in, or sign in with email.")
        st.caption("Your documents and conversations belong to your account. A full browser reload requires signing in again.")
    with sign_up:
        with st.form("signup", clear_on_submit=True):
            name = st.text_input("Name", max_chars=80)
            email = st.text_input("Email address", max_chars=254)
            password = st.text_input("Choose password (at least 8 characters)", type="password")
            confirm = st.text_input("Repeat password", type="password")
            submitted = st.form_submit_button("Create account", disabled=not configured)
        if submitted:
            if not name.strip() or "@" not in email or len(password) < 8 or password != confirm:
                st.error("Enter a name, valid email and matching passwords of at least 8 characters.")
            else:
                try:
                    res = client().auth.sign_up({"email": email.strip(), "password": password,
                        "options": {"data": {"full_name": name.strip()}, "email_redirect_to": config("REDIRECT_URL", "https://adaptive-rag1.streamlit.app/")}})
                    if res.session:
                        accept_session(st.session_state, res)
                        st.rerun()
                    else:
                        st.success("Check your email to confirm your account, then sign in.")
                except Exception as exc:
                    failure("Account creation", exc)
    with recover:
        st.write("Request a reset email, then follow its link to choose a new password.")
        with st.form("request_reset", clear_on_submit=True):
            email = st.text_input("Account email")
            submitted = st.form_submit_button("Send reset email", disabled=not configured)
        if submitted and email.strip():
            try:
                client().auth.reset_password_email(email.strip(), {"redirect_to": config("REDIRECT_URL", "https://adaptive-rag1.streamlit.app/")})
                st.success("If an account exists, a reset email has been sent.")
            except Exception as exc:
                failure("Password reset", exc)
    with lab:
        evidence_lab()


def recovery_page():
    st.subheader("Choose a new password")
    with st.form("change_password", clear_on_submit=True):
        password = st.text_input("New password", type="password")
        confirm = st.text_input("Confirm new password", type="password")
        submit = st.form_submit_button("Update password")
    if submit:
        if len(password) < 8 or password != confirm:
            st.error("Enter matching passwords of at least 8 characters.")
        else:
            try:
                client().auth.update_user({"password": password})
                st.session_state.pop("recovery", None)
                st.rerun()
            except Exception as exc:
                failure("Password update", exc)


def readable(text: str) -> str:
    """Keep currency in generated prose from becoming Markdown math."""
    return text.replace("$", r"\$")


def show_report(report: dict, key: str, repo=None):
    status = {"supported": "Supported", "partial": "Partial evidence", "abstained": "No supported answer"}
    st.caption(status.get(report.get("status"), "Saved evidence"))
    view = st.selectbox("Show details", ["Sources & quotes", "Disagreements & limits", "Source dependency",
        "Retrieval steps", "Withheld claims"], key=f"detail_view_{key}", label_visibility="collapsed")
    if view == "Sources & quotes":
        sources = {s["id"]: s for s in report.get("sources", [])}
        if not report.get("claims"):
            st.caption("No claim passed the evidence checks. See disagreements & limits for details.")
        for i, claim in enumerate(report.get("claims", []), 1):
            st.markdown(f"**Claim {i}** · {readable(claim['claim'])}")
            for citation in claim["evidence"]:
                source = sources[citation["id"]]
                page = f" · page {source['page']}" if source.get("page") else ""
                st.caption(f"[{citation['id']}] {source['source']}{page}")
                st.code(citation["quote"], language=None, wrap_lines=True)
    elif view == "Disagreements & limits":
        for disagreement in report.get("disagreements", []):
            st.warning(readable(f"{disagreement['kind'].replace('_', ' ').title()}: {disagreement['explanation']}"))
        for limitation in report.get("limitations", []):
            st.write(readable(limitation))
        if not report.get("limitations") and not report.get("disagreements"):
            st.caption("No disagreements or limitations were reported for this answer. Model checks can still make mistakes.")
    elif view == "Withheld claims":
        for claim in report.get("rejected_claims", []):
            st.write(readable(claim["claim"]))
            st.caption(readable(claim["reason"]))
        if not report.get("rejected_claims"):
            st.caption("No proposed claims were withheld.")
    elif view == "Source dependency":
        data = report.get("stress", {})
        st.caption("If one document's citations disappear, how much of this answer keeps support?")
        for row in data.get("removals", []):
            st.write(f"**{row['source']}** · {row['retained_fraction']:.0%} of claims retain a citation")
            if row["unsupported_claims"]:
                st.caption("Claims without support: " + ", ".join(map(str, row["unsupported_claims"])))
        st.caption(data.get("limitation", "No validated claims to test."))
        if repo and report.get("question"):
            cited_docs = {s["document_id"]: s["source"] for s in report.get("sources", []) if s.get("document_id")}
            if cited_docs:
                st.divider()
                st.write("**Try the answer without a source**")
                omitted = st.selectbox("Document to omit", list(cited_docs), format_func=cited_docs.get, key=f"omit_choice_{key}")
                if st.button("Re-run without this document", key=f"omit_run_{key}"):
                    try:
                        with st.spinner("Checking the remaining sources…"):
                            st.session_state[f"omission_{key}"] = omission_experiment(report["question"], repo.corpus(), omitted,
                                model, embed, report.get("history", []))
                    except Exception as exc:
                        failure("Source omission experiment", exc)
                alternate = st.session_state.get(f"omission_{key}")
                if alternate:
                    st.write("**Alternative answer**")
                    st.write(readable(alternate["answer"]))
                    st.caption(f"{alternate['experiment']['remaining_passages']} passages searched with the selected document excluded.")
                    alternate_sources = {s["id"]: s for s in alternate.get("sources", [])}
                    for claim in alternate.get("claims", []):
                        for citation in claim["evidence"]:
                            source = alternate_sources[citation["id"]]
                            st.caption(f"[{citation['id']}] {source['source']} · page {source.get('page') or 'web'}")
                            st.code(citation["quote"], language=None, wrap_lines=True)
                    for limitation in alternate.get("limitations", []):
                        st.caption(readable(limitation))
                    st.caption(alternate["experiment"].get("limitation", "Model and retrieval variation can affect this comparison."))
                    st.download_button("Export alternative report", json.dumps(alternate,indent=2,ensure_ascii=False),
                        file_name="sourcemind-omission.json",mime="application/json",key=f"export_alternate_{key}")
    elif view == "Retrieval steps":
        st.caption("Search queries, retrieved passages, and evidence checks for this answer.")
        for stage in report.get("trace", []):
            st.json(stage, expanded=False)
        st.json(report.get("metrics", {}), expanded=False)
    st.download_button("Export evidence report", json.dumps(report, indent=2, ensure_ascii=False),
                       file_name="sourcemind-evidence.json", mime="application/json", key=f"export_{key}", icon=":material/download:")


def evidence_lab():
    from sourcemind.lab import demo_corpus, demo_cases, fixture_model
    st.subheader("Evidence Lab")
    st.write("A reproducible engineering demonstration: conflicting numbers, missing evidence and source dependency.")
    st.caption("Uses public synthetic passages and deterministic fixtures. This demonstrates pipeline checks; it is not a live AI quality benchmark.")
    selected = st.selectbox("Challenge", list(demo_cases()))
    case = demo_cases()[selected]
    st.write(case["question"])
    if st.button("Run challenge", key="run_lab", type="primary"):
        st.session_state["lab_report"] = answer(case["question"], demo_corpus(), fixture_model(case))
        st.session_state["lab_selected"] = selected
    if st.session_state.get("lab_report") and st.session_state.get("lab_selected") == selected:
        report = st.session_state["lab_report"]
        st.write(report["answer"])
        show_report(report, "lab")
    with st.expander("Inspect the synthetic source passages"):
        for p in demo_corpus():
            st.caption(f"{p.source} · page {p.page}")
            st.code(p.text, language=None, wrap_lines=True)


def open_page(page: str, conversation_id: str | None = None):
    st.session_state["workspace_page"] = page
    if page == "Ask & inspect":
        if conversation_id:
            st.session_state["conversation_id"] = conversation_id
        else:
            st.session_state.pop("conversation_id", None)


def workspace(user: dict):
    repo = Repository(client(), user["id"])
    docs = repo.documents()
    page = st.session_state.get("workspace_page", "Ask & inspect")
    with st.sidebar:
        with st.container(key="sidebar-nav"):
            st.markdown("### ◈ SourceMind")
            st.button("New chat", icon=":material/edit_square:", use_container_width=True,
                      on_click=open_page, args=("Ask & inspect",))
            st.button("Sources", icon=":material/folder_open:", use_container_width=True,
                      type="primary" if page == "Source library" else "secondary",
                      on_click=open_page, args=("Source library",))
            with st.popover("Tools", icon=":material/apps:", use_container_width=True):
                for tool, icon in [("PDF disagreements", "compare_arrows"), ("Knowledge gaps", "search"), ("Evidence Lab", "science")]:
                    st.button(tool, icon=f":material/{icon}:", use_container_width=True,
                              on_click=open_page, args=(tool,))
        with st.container(key="sidebar-chats"):
            st.caption("Your chats")
            for conv in repo.conversations()[:25]:
                st.button(conv["title"], key=f"conv_{conv['id']}", use_container_width=True,
                          type="primary" if page == "Ask & inspect" and st.session_state.get("conversation_id") == conv["id"] else "secondary",
                          on_click=open_page, args=("Ask & inspect", conv["id"]))
        with st.container(key="sidebar-account"):
            with st.popover(user["name"], icon=":material/account_circle:", use_container_width=True):
                st.caption(user["email"])
                if st.button("Sign out", use_container_width=True):
                    try:
                        client().auth.sign_out({"scope": "local"})
                    except Exception:
                        pass
                    clear_session(st.session_state)
                    st.query_params.clear()
                    st.rerun()
    if page == "Ask & inspect":
        title, options = st.columns([4, 1])
        with title:
            st.caption("ASK & INSPECT")
        with options:
            with st.popover("Options", use_container_width=True):
                depth = st.radio("Answer depth", ["Adaptive", "Forensic"], key="investigation_mode",
                    index=["Adaptive", "Forensic"].index(st.session_state.get("answer_depth", "Adaptive")),
                    help="Forensic plans multiple searches. Both modes check quotes and audit support.")
                st.session_state["answer_depth"] = depth
                st.caption(f"{len(docs)} private sources · {sum(d.get('indexed_chunks', 0) for d in docs)} searchable passages")
        mode = st.session_state.get("investigation_mode", "Adaptive")
        conversation_id = st.session_state.get("conversation_id")
        history = repo.messages(conversation_id) if conversation_id else []
        if not history:
            st.markdown("<div class='welcome'><h1>What would you like to know?</h1><p>Ask a question. Get an answer grounded in your sources.</p></div>", unsafe_allow_html=True)
        for msg in history:
            with st.chat_message(msg["role"]):
                st.write(readable(msg["content"]))
                if msg.get("evidence_report"):
                    report = msg["evidence_report"]
                    if report.get("disagreements"):
                        st.caption("Sources disagree · Open details to compare the evidence.")
                    elif report.get("status") in {"partial", "abstained"}:
                        st.caption("Limited evidence · Open details to see what could be established.")
                    with st.expander("View sources & details"):
                        show_report(report, msg["id"], repo)
        if not docs:
            st.info("Add your first document from Sources in the sidebar.")
        question = st.chat_input("Ask a question across your documents", disabled=not docs, max_chars=2000)
        if question:
            try:
                if not conversation_id:
                    conversation_id = repo.create_conversation(question)
                    st.session_state["conversation_id"] = conversation_id
                repo.save_message(conversation_id, "user", question)
                with st.spinner("Retrieving passages, checking quotes and auditing claims…"):
                    report = answer(question, repo.corpus(), model, embed=embed, history=history, mode=mode.lower())
                repo.save_message(conversation_id, "assistant", report["answer"], report)
                st.rerun()
            except Exception as exc:
                failure("Answer generation or saving", exc)
    elif page == "Source library":
        st.subheader("Add evidence to your private library")
        st.caption("PDFs: up to 15 MB / 200 pages / 500 passages per source. Workspace: 3,000 passages. Text is sent to Groq when answering or checking disagreements.")
        uploads = st.file_uploader("PDF documents", type=["pdf"], accept_multiple_files=True)
        urls = st.text_area("Public web pages (one URL per line)", max_chars=4000)
        if st.button("Index sources", type="primary"):
            inputs = [("pdf", f) for f in uploads or []] + [("url", u.strip()) for u in urls.splitlines() if u.strip()]
            if not inputs:
                st.warning("Choose a PDF or enter a web page URL.")
            for kind, source in inputs[:10]:
                try:
                    with st.spinner("Extracting pages and storing searchable passages…"):
                        doc = read_pdf(source.getvalue(), source.name) if kind == "pdf" else read_url(source)
                        if doc["fingerprint"] in {d.get("fingerprint") for d in repo.documents()}:
                            st.info(f"Already indexed: {doc['name']}")
                            continue
                        vectors = encoder().encode([c["content"] for c in doc["chunks"]], normalize_embeddings=True, batch_size=32).tolist()
                        result = repo.ingest(doc, vectors)
                        st.success(f"{doc['name']}: {result.get('chunks', 0)} passages stored ({result['status']}).")
                        st.session_state.pop("scan_report", None)
                except ValueError as exc:
                    st.error(str(exc))
                except Exception as exc:
                    failure("Document indexing", exc)
            if len(inputs) > 10:
                st.warning("Only the first 10 sources were processed. Add the remainder in another batch.")
        st.divider()
        for doc in repo.documents():
            with st.expander(doc["name"]):
                st.caption(f"{doc.get('page_count') or '?'} pages · {doc['indexed_chunks']} durable passages · {doc.get('added_at', '')[:10]}")
                st.write(doc.get("summary", ""))
                if not doc["indexed_chunks"]:
                    st.warning("This legacy record has no durable passages. Re-upload the original PDF to restore searchable evidence; then remove this old record.")
                consent = st.checkbox("Remove this source and its stored passages", key=f"remove_ok_{doc['id']}")
                if st.button("Remove source", disabled=not consent, key=f"remove_{doc['id']}"):
                    repo.delete_document(doc["id"])
                    st.session_state.pop("scan_report", None)
                    st.rerun()
    elif page == "PDF disagreements":
        st.subheader("Where your PDFs disagree")
        st.write("Compare topical passages across documents, with exact quotations and page numbers on both sides. Historical changes and different scopes are shown separately.")
        budget = st.select_slider("Comparison budget", options=[12, 24, 48], value=12)
        if st.button("Check cross-document disagreements", disabled=len(docs) < 2):
            try:
                with st.spinner("Comparing passages and checking quotation provenance…"):
                    report = contradiction_scan(repo.corpus(), model, max_pairs=budget)
                    repo.save_scan(report)
                    st.session_state["scan_report"] = report
            except Exception as exc:
                failure("Disagreement scan", exc)
        report = st.session_state.get("scan_report")
        if report:
            st.caption(f"{report['checked_pairs']} pairs assessed · {report['unexamined_pairs']} candidate pairs outside budget · {report['failed_pairs']} failed checks")
            st.caption(report["note"])
            findings = report["findings"]
        else:
            findings = [r["finding"] for r in repo.rows("conflicts") if r.get("finding")]
        for finding in findings:
            with st.expander(f"{finding['kind'].replace('_', ' ').title()} · {finding['topic']}"):
                left, right = st.columns(2)
                for col, side in [(left, "a"), (right, "b")]:
                    with col:
                        st.caption(f"{finding[f'source_{side}']} · page {finding.get(f'page_{side}') or 'web'}")
                        st.code(finding[f"quote_{side}"], language=None, wrap_lines=True)
                st.write(readable(finding["explanation"]))
        if report and not findings:
            st.info("No disagreements found in the assessed pairs. This does not establish that all documents agree.")
        if report:
            st.download_button("Download disagreement report", json.dumps(report, indent=2), "sourcemind-disagreements.json", "application/json")
    elif page == "Evidence Lab":
        evidence_lab()

    elif page == "Knowledge gaps":
        st.subheader("Which questions can your evidence support?")
        st.write("Probe up to three questions. A gap means no answer passed the evidence checks; it does not prove the information is absent from every page.")
        with st.form("coverage_probes"):
            questions = st.text_area("Probe questions (one per line)", max_chars=3000)
            run = st.form_submit_button("Check evidence coverage", disabled=not docs)
        if run:
            try:
                corpus = repo.corpus()
                probes = [q.strip() for q in questions.splitlines() if q.strip()][:3]
                with st.spinner("Testing whether the retrieved evidence supports each question…"):
                    st.session_state["coverage_reports"] = [(q, answer(q, corpus, model, embed)) for q in probes]
            except Exception as exc:
                failure("Coverage check", exc)
        for i, (question, report) in enumerate(st.session_state.get("coverage_reports", [])):
            with st.expander(question):
                st.write("Evidence gap" if report["status"] == "abstained" else "Evidence found" if report["status"] == "supported" else "Partial coverage")
                st.write(report["answer"])
                show_report(report, f"coverage_{i}")


def main():
    try:
        oauth_callback()
        user = ensure_session(st.session_state, client()) if st.session_state.get("user") else None
        if user and st.session_state.get("recovery"):
            recovery_page()
        elif user:
            workspace(user)
        else:
            login_page()
    except AuthExpired as exc:
        st.warning(str(exc))
        login_page()
    except Exception as exc:
        failure("Workspace loading", exc)
        st.button("Retry", on_click=lambda: None)


if __name__ == "__main__":
    main()
